name: Build and Publish image to Docker Hub 
on: 
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  publish_images:
    runs-on:ubuntu-latest
 
  steps:
  - name: Checkout code
    uses: actions/checkout@v4 
  - name: build image 
    run: docker build ./ -t ghcr.io/robsieg/dev-graph-data-webapp:latest
  - name: push image to github container hub
    run: docker push ghcr.io/robsieg/dev-graph-data-webapp:latest