FROM python

EXPOSE 8501

WORKDIR /app

RUN apt update 

COPY requirements.txt requirements.txt 

COPY app/ /app/

RUN pip install -r requirements.txt

CMD [ "streamlit", "run", "streamlit_app.py"]



