name: Build and Publish image to Docker Hub 
on: 

 [workflow_dispatch] 

# push:
#   branches: [dev]
#  pull_request:
#    branches:
#      - dev


jobs:
  publish_images:
    runs-on: ubuntu-latest
 
  steps:
      name: Checkout
      uses: actions/checkout@v4 
      name: build-image 
      run: docker build ./app -t ghcr.io/robsieg/dev-graph-data-webapp:latest
      name: push_image_to_ghcr
      run: docker push ghcr.io/robsieg/dev-graph-data-webapp:latest
