name: Build and Publish image to Docker Hub
on:
  workflow_dispatch:

jobs:
  publish_images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: build-image
        run: docker build /workspaces/codespaces-blank/app -t ghcr.io/robsieg/dev-graph-data-webapp:latest
      - name: push_image_to_ghcr
        run: docker push ghcr.io/robsieg/dev-graph-data-webapp:latest
