name: Build & Publish DEV image to GHCR
on:
  workflow_dispatch:
  push:
    branches:
      
      - dev 
  pull_request:
    branches:
      
      - dev

jobs:
  Build_Publish_DEV_image:
    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t ghcr.io/robsieg/dev-graph-data-webapp:latest ./app
      - name: Login to GHCR
        run: echo "${{ secrets.DEV_GHCR}}" | docker login ghcr.io -u robsieg --password-stdin
      - name: Push Docker Image to GHCR
        run: docker push ghcr.io/robsieg/dev-graph-data-webapp:latest
