name: Build & Publish PROD image to GHCR
on:
  workflow_dispatch:
  push:
    branches:
      - main
       
  pull_request:
    branches:
      - main
      

jobs:
  publish_images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t ghcr.io/robsieg/prod-graph-data-webapp:latest ./app
      - name: Login to GHCR
        run: echo "${{ secrets.DEV_GHCR}}" | docker login ghcr.io -u robsieg --password-stdin
      - name: Push Docker Image to GHCR
        run: docker push ghcr.io/robsieg/prod-graph-data-webapp:latest
